"""Generate src/data/thermo.ts: standard enthalpy of formation (kJ/mol, 25 °C) for the compound database.

Source: the `chemicals` Python package (MIT licence) — pip install chemicals
Run:    python scripts/generate-thermo.py
Each value is for the compound in the physical state ChemSim lists for it (gas / liquid / solid).
Different reference tables can disagree by about ±1 kJ/mol; these are educational values.
"""
import warnings
from pathlib import Path
from chemicals import Hfs, Hfl, Hfg
warnings.filterwarnings('ignore')

# formula: (CAS number, phase)
SPECIES = {
    'H2O': ('7732-18-5', 'l'), 'CO2': ('124-38-9', 'g'), 'NaCl': ('7647-14-5', 's'), 'NH3': ('7664-41-7', 'g'), 'CH4': ('74-82-8', 'g'),
    'CaO': ('1305-78-8', 's'), 'CaCl2': ('10043-52-4', 's'), 'HCl': ('7647-01-0', 'g'), 'NO2': ('10102-44-0', 'g'),
    'NaOH': ('1310-73-2', 's'), 'H2SO4': ('7664-93-9', 'l'), 'H2O2': ('7722-84-1', 'l'), 'CO': ('630-08-0', 'g'), 'SO2': ('7446-09-5', 'g'),
    'H2S': ('7783-06-4', 'g'), 'HF': ('7664-39-3', 'g'), 'KCl': ('7447-40-7', 's'), 'LiF': ('7789-24-4', 's'), 'MgO': ('1309-48-4', 's'),
    'MgCl2': ('7786-30-3', 's'), 'AlCl3': ('7446-70-0', 's'), 'Al2O3': ('1344-28-1', 's'), 'Fe2O3': ('1309-37-1', 's'),
    'FeCl3': ('7705-08-0', 's'), 'ZnO': ('1314-13-2', 's'), 'CuO': ('1317-38-0', 's'), 'KOH': ('1310-58-3', 's'),
    'Ca(OH)2': ('1305-62-0', 's'), 'Na2SO4': ('7757-82-6', 's'), 'MgSO4': ('7487-88-9', 's'), 'CuSO4': ('7758-98-7', 's'),
    'CaCO3': ('471-34-1', 's'), 'Na2CO3': ('497-19-8', 's'), 'NaHCO3': ('144-55-8', 's'), 'KNO3': ('7757-79-1', 's'),
    'NH4Cl': ('12125-02-9', 's'), 'HNO3': ('7697-37-2', 'l'),
}
FN = {'s': Hfs, 'l': Hfl, 'g': Hfg}
rows, missing = [], []
for formula, (cas, phase) in SPECIES.items():
    try:
        v = FN[phase](cas)
    except Exception:
        v = None
    if v is None: missing.append(formula); continue
    rows.append(f"  '{formula}': {round(v / 1000, 1)},")

Path(__file__).resolve().parent.parent.joinpath('src/data/thermo.ts').write_text(
    "// GENERATED by scripts/generate-thermo.py — do not edit by hand. Source: `chemicals` package (MIT licence).\n"
    "// Standard enthalpy of formation in kJ/mol at 25 °C, for each compound in the state ChemSim lists for it.\n"
    "// Elements in their standard states (H2, O2, C graphite, Na, ...) are 0 by definition. Sources can differ by about ±1 kJ/mol.\n"
    "export const FORMATION_ENTHALPY: Record<string, number> = {\n" + "\n".join(rows) + "\n};\n")
print('wrote', len(rows), 'values; missing:', missing or 'none')
