"""Generate src/data/elements.ts for all 118 elements.

Source: the `mendeleev` Python package (MIT licence) — pip install mendeleev
Run:    python scripts/generate-elements.py

Hand-curated values in curated.json win over the generated ones for the first 49 elements, because the
engine depends on the ORDER of oxidation states (most common first; a negative first state marks an anion).
"""
import json, re, warnings
from pathlib import Path
from mendeleev import element
warnings.filterwarnings('ignore')

ROOT = Path(__file__).resolve().parent
CUR = json.load(open(ROOT / 'curated.json'))
NAME_FIX = {'Aluminum': 'Aluminium', 'Cesium': 'Caesium'}
STATE_FIX = {'Mo': [6, 4], 'W': [6, 4], 'Tc': [7, 4], 'Eu': [3, 2], 'Yb': [3, 2], 'Sm': [3, 2]}

def category(z, sym, group):
    if sym == 'H': return 'nonmetal'
    if group == 1: return 'alkali'
    if group == 2: return 'alkaline'
    if group == 17: return 'halogen'
    if group == 18: return 'noble'
    if 57 <= z <= 71: return 'lanthanide'
    if 89 <= z <= 103: return 'actinide'
    if sym in {'B', 'Si', 'Ge', 'As', 'Sb', 'Te'}: return 'metalloid'
    if sym in {'C', 'N', 'O', 'P', 'S', 'Se'}: return 'nonmetal'
    if group is not None and 3 <= group <= 12: return 'transition'
    return 'post-transition'

def valence(econf, period):  # electrons in the outermost s and p subshells (n = period)
    return sum(int(c or 1) for n, l, c in re.findall(r'(\d)([spdf])(\d*)', econf) if int(n) == period and l in 'sp')

def states(sym, cat, raw):
    if sym in CUR: return CUR[sym]['states']
    if cat == 'noble': return [0]
    if sym in STATE_FIX: return STATE_FIX[sym]
    neg = [x for x in raw if x < 0]; pos = [x for x in raw if x > 0]
    anion_like = cat in ('nonmetal', 'halogen') or sym == 'Te'
    return neg + pos if anion_like else pos + neg  # metals/metalloids: positive states first

rows, issues = [], []
f_index = {}
for z in range(1, 119):
    e = element(z); sym = e.symbol
    group = e.group_id if e.group_id else None
    cat = category(z, sym, group)
    name = CUR[sym]['name'] if sym in CUR else NAME_FIX.get(e.name, e.name)
    mass = f"{round(e.atomic_weight, 3):.3f}".rstrip('0').rstrip('.')
    val = valence(e.econf, e.period)
    if sym in CUR:
        if CUR[sym]['category'] != cat: issues.append(f'{sym}: category {CUR[sym]["category"]} vs {cat}')
        if CUR[sym]['valence'] != val: issues.append(f'{sym}: valence {CUR[sym]["valence"]} vs {val}')
        val = CUR[sym]['valence']
    if group is None:  # f-block rows sit below the main table (La and Ac stay in group 3)
        series = 'La' if 58 <= z <= 71 else 'Ac'
        f_index[series] = f_index.get(series, 0) + 1
        row, col = (9 if series == 'La' else 10), 2 + f_index[series]
    else:
        row, col = e.period, group
    rows.append(f"  [{z}, '{sym}', '{name}', {mass}, '{cat}', {val}, {json.dumps(states(sym, cat, e.oxistates))}, {e.period}, {group if group else 'null'}, {row}, {col}],")

out = """// GENERATED by scripts/generate-elements.py — do not edit by hand.
// Source: mendeleev (MIT licence). Atomic masses rounded to 3 decimals; for radioactive elements the value is
// the mass number of the longest-lived isotope. Oxidation states are "common" states, most common first
// (curated for the first 49 elements, derived from mendeleev for the rest; [] = not well established).
import type { Category, Element } from '../models';

// [Z, symbol, name, mass, category, valence e-, oxidation states, period, group, grid row, grid column]
type Row = [number, string, string, number, Category, number, number[], number, number | null, number, number];
const ROWS: Row[] = [
""" + "\n".join(rows) + """
];

export const ELEMENTS: Element[] = ROWS.map(([atomicNumber, symbol, name, atomicMass, category, valenceElectrons, commonOxidationStates, period, group, row, col]) =>
  ({ atomicNumber, symbol, name, atomicMass, category, valenceElectrons, commonOxidationStates, period, group, row, col }));

export const ELEMENT_BY_SYMBOL: Record<string, Element> = Object.fromEntries(ELEMENTS.map((e) => [e.symbol, e]));

/** Elements shown in the "Choose Elements" row by default. */
export const QUICK_ELEMENTS = ['H', 'O', 'C', 'N', 'Na', 'Cl'];
"""
(ROOT.parent / 'src/data/elements.ts').write_text(out)
print('wrote', len(rows), 'elements; curated/derived mismatches:', issues or 'none')


# ---------------------------------------------------------------------------------------------
# Atomic structure: electron configuration, electron shells and isotopes  →  src/data/atomic-structure.ts
# ---------------------------------------------------------------------------------------------
CORES = {
    'He': '1s2', 'Ne': '1s2 2s2 2p6', 'Ar': '1s2 2s2 2p6 3s2 3p6',
    'Kr': '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6', 'Xe': '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6',
    'Rn': '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6',
}
SUP = str.maketrans('', '', '')

def structure(z, e):
    toks = re.findall(r'\[(\w+)\]|(\d)([spdf])(\d*)', e.econf)
    shells, shown = {}, []
    for core, n, l, c in toks:
        if core:
            shown.append(f'[{core}]')
            for n2, _, c2 in re.findall(r'(\d)([spdf])(\d+)', CORES[core]):
                shells[int(n2)] = shells.get(int(n2), 0) + int(c2)
        else:
            c = int(c or 1)
            shown.append(f'{n}{l}{c}')
            shells[int(n)] = shells.get(int(n), 0) + c
    assert sum(shells.values()) == z, (e.symbol, shells)
    natural = sorted((i.mass_number, i.abundance, i.is_radioactive) for i in e.isotopes if i.abundance)
    if natural:
        a, _, rad = max(natural, key=lambda t: t[1])
    else:  # no natural isotopes: the mass number the source uses for its atomic mass
        a, rad = round(e.atomic_weight), True
    return ' '.join(shown), [shells[n] for n in sorted(shells)], a, rad, [(m, round(ab, 4)) for m, ab, _ in natural]

lines = []
for z in range(1, 119):
    e = element(z)
    cfg, sh, a, rad, nat = structure(z, e)
    assert a >= z, (e.symbol, a)
    nat_ts = ', '.join(f'[{m}, {ab:g}]' for m, ab in nat)
    lines.append(f"  {e.symbol}: {{ config: '{cfg}', shells: {sh}, massNumber: {a}, radioactive: {str(rad).lower()}, natural: [{nat_ts}] }},")

(ROOT.parent / 'src/data/atomic-structure.ts').write_text("""// GENERATED by scripts/generate-elements.py — do not edit by hand. Source: mendeleev (MIT licence).
// massNumber: the most abundant natural isotope; for elements with no natural isotopes, the mass number used for
// the element's atomic mass (a representative, long-lived isotope). radioactive: that isotope is unstable.
// natural: [mass number, abundance %] for naturally occurring isotopes.
export interface AtomicStructureData {
  config: string;
  shells: number[];
  massNumber: number;
  radioactive: boolean;
  natural: [number, number][];
}

export const ATOMIC_STRUCTURE: Record<string, AtomicStructureData> = {
""" + "\n".join(lines) + "\n};\n")
print('atomic structure written:', len(lines))
