"""Generate src/data/phase-data.ts: melting and boiling points (°C, 1 atm) for all elements and the compound database.

Sources: `mendeleev` (elements) and `chemicals` (compounds), both MIT-licensed — pip install mendeleev chemicals
Run:     python scripts/generate-phase-data.py

The curated tables below correct values that are wrong in the source, and flag compounds that decompose or sublime
instead of simply melting and boiling. Decomposition temperatures are approximate (educational values).
"""
import warnings
from pathlib import Path
from chemicals import Tb, Tm
from mendeleev import element
from species import SPECIES
warnings.filterwarnings('ignore')

C = lambda k: None if k is None else round(float(k) - 273.15, 1)

# Source values that disagree with standard references (checked by hand): formula -> corrected melting point (°C)
MP_FIX = {'HCl': -114.2, 'H2O2': -0.4}
# Elements whose source values are missing because of allotropes or sublimation (standard literature values, °C):
# white phosphorus; rhombic sulfur; grey selenium; white tin; carbon sublimes (melting = boiling point used as the sublimation point)
EL_FIX = {'P': (44.2, 280.5), 'S': (115.2, 444.7), 'Se': (221.0, 685.0), 'Sn': (231.9, 2602.0), 'C': (3642.0, 3642.0)}
# Compounds that decompose before they melt/boil: formula -> (approx. °C, note)
DECOMPOSES = {
    'CaCO3': (825, 'Decomposes into CaO and CO2 instead of melting.'),
    'Ca(OH)2': (580, 'Decomposes into CaO and water instead of melting.'),
    'NaHCO3': (100, 'Decomposes into Na2CO3, water and CO2 on heating.'),
    'CuSO4': (650, 'Decomposes on strong heating instead of melting.'),
    'MgSO4': (1124, 'Decomposes on strong heating instead of melting.'),
    'KNO3': (400, 'Melts, then decomposes (releasing oxygen) on stronger heating.'),
}
# Compounds that go straight from solid to gas at 1 atm: formula -> (°C, note)
SUBLIMES = {'NH4Cl': (338, 'Sublimes and breaks down into NH3 and HCl instead of melting.')}

elements = {}
for z in range(1, 119):
    e = element(z)
    elements[e.symbol] = (C(e.melting_point), C(e.boiling_point))

elements.update(EL_FIX)

compounds = {}
for f, (cas, _) in SPECIES.items():
    mp, bp = C(Tm(cas)), C(Tb(cas))
    mp = MP_FIX.get(f, mp)
    entry = {'mp': mp, 'bp': bp}
    if f in DECOMPOSES: entry['decomposesAt'], entry['note'] = DECOMPOSES[f]
    if f in SUBLIMES: entry['sublimesAt'], entry['note'] = SUBLIMES[f]
    compounds[f] = entry

js = lambda v: 'null' if v is None else repr(v)
el_lines = [f"  {s}: [{js(mp)}, {js(bp)}]," for s, (mp, bp) in elements.items()]
co_lines = []
for f, d in compounds.items():
    extra = ''.join(f", {k}: {v!r}" if k != 'note' else f", note: {v!r}" for k, v in d.items() if k not in ('mp', 'bp'))
    co_lines.append(f"  '{f}': {{ mp: {js(d['mp'])}, bp: {js(d['bp'])}{extra} }},")

Path(__file__).resolve().parent.parent.joinpath('src/data/phase-data.ts').write_text(
    "// GENERATED by scripts/generate-phase-data.py — do not edit by hand.\n"
    "// Melting / boiling points in °C at 1 atm (pressure is not modelled). Sources: mendeleev (elements), chemicals (compounds),\n"
    "// with a few corrections and decomposition/sublimation flags curated in the script. null = not available at 1 atm.\n"
    "import type { PhaseData } from '../models';\n\n"
    "/** [melting °C, boiling °C] */\nexport const ELEMENT_PHASE: Record<string, [number | null, number | null]> = {\n" + "\n".join(el_lines) + "\n};\n\n"
    "export const COMPOUND_PHASE: Record<string, PhaseData> = {\n" + "\n".join(co_lines) + "\n};\n")
odd = [s for s, (mp, bp) in elements.items() if mp is not None and bp is not None and mp > bp]
print('elements:', len(el_lines), '| compounds:', len(co_lines), '| elements with melting > boiling (sublimation):', odd)
