"""Generate src/data/thermo.ts: standard enthalpy of formation (kJ/mol, 25 °C) for the compound database.

Source: the `chemicals` Python package (MIT licence) — pip install chemicals
Run:    python scripts/generate-thermo.py
Each value is for the compound in the physical state ChemSim lists for it (gas / liquid / solid).
Different reference tables can disagree by about ±1 kJ/mol; these are educational values.
"""
import warnings
from pathlib import Path
from chemicals import Hfs, Hfl, Hfg
warnings.filterwarnings('ignore')

from species import SPECIES

FN = {'s': Hfs, 'l': Hfl, 'g': Hfg}
rows, missing = [], []
for formula, (cas, phase) in SPECIES.items():
    try:
        v = FN[phase](cas)
    except Exception:
        v = None
    if v is None: missing.append(formula); continue
    rows.append(f"  '{formula}': {round(v / 1000, 1)},")

Path(__file__).resolve().parent.parent.joinpath('src/data/thermo.ts').write_text(
    "// GENERATED by scripts/generate-thermo.py — do not edit by hand. Source: `chemicals` package (MIT licence).\n"
    "// Standard enthalpy of formation in kJ/mol at 25 °C, for each compound in the state ChemSim lists for it.\n"
    "// Elements in their standard states (H2, O2, C graphite, Na, ...) are 0 by definition. Sources can differ by about ±1 kJ/mol.\n"
    "export const FORMATION_ENTHALPY: Record<string, number> = {\n" + "\n".join(rows) + "\n};\n")
print('wrote', len(rows), 'values; missing:', missing or 'none')
